name: _selfhostedtest

on:
  schedule:
    - cron: "35 5 * * 5"
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: self-hosted

    steps:
      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Stationshuiskamer -Scope CurrentUser

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-StationsHuiskamer