name: boekuitdekast

on:
  schedule:
    - cron: "36 9 * * 5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Nrc, UncommonSense.Rss -Scope CurrentUser -Force

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-BoekUitDeKast
          | Select-Object -First 10
          | ForEach-Object {
            $Description = (($_.Body | ForEach-Object { $_.Trim()} | Where-Object {$_} | ForEach-Object { "<p>$($_)</p>"}) -join "`n") + "`n<img src='$($_.Image)'/>"

            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description $Description `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Boek uit de kast' `
            -Link 'https://www.nrc.nl/rubriek/boek-uit-de-kast/' `
            -Description 'Boek uit de kast'
          | Set-Content -Path ./data/boekuitdekast.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
