name: demeerse

on:
  schedule:
    - cron: "0 2 * * *" # GitHub uses UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DataFolderName: ./data/theatre

    steps:
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Theatre, UncommonSense.Hap, UncommonSense.iCalendar -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update calendar file
        shell: pwsh
        run: |
          Get-DeMeerseHoofddorp
          | ForEach-Object { New-CalendarEvent -Start $_.Date -End ($_.Date).AddHours(2) -Summary "De Meerse: $($_.Genre): $($_.Artist) $($_.Title)" -Description "<img src='$($_.Image)'>" }
          | Export-Calendar -Name 'De Meerse Hoofddorp' -Path (Join-Path -Path $env:DataFolderName -ChildPath demeerse.ics)

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git pull
          git add ./data/theatre/*
          git commit -am 'Updated threatre files'
          git push
