name: filmhuisalkmaar

on:
  schedule:
    - cron: "45 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
        DataFolderName: ./data/cinema

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Cinema, UncommonSense.iCalendar -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update calendar file
        shell: pwsh
        run: |
          Get-FilmhuisAlkmaar -Verbose
          | ForEach-Object { New-CalendarEvent -Start $_.Date -End ($_.Date).AddHours(2) -Summary "Filmhuis Alkmaar: $($_.Title)" -Description $_.Body }
          | Export-Calendar -Name 'Filmhuis Alkmaar' -Path (Join-Path -Path $env:DataFolderName -ChildPath filmhuisalkmaar.ics)

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
