name: fokkesukke2

on:
  schedule:
    - cron: "40 5 * * 1-6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Nrc, UncommonSense.Pushover -Scope CurrentUser

      - name: Send notification
        shell: pwsh
        env:
          PUSHOVER_APP_FOKKESUKKE: ${{secrets.PUSHOVER_APP_FOKKESUKKE}}
          PUSHOVER_USER_FOKKESUKKE: ${{secrets.PUSHOVER_USER_FOKKESUKKE}}
        run: |
          Get-FokkeSukke
          | Select-Object -First 1
          | ForEach-Object {
            Send-PushoverNotification `
              -ApplicationToken $env:PUSHOVER_APP_FOKKESUKKE `
              -Recipient $env:PUSHOVER_USER_FOKKESUKKE `
              -Attachment $_.Body `
              -Message 'FIXME' `
              -Title ('Fokke & Sukke: {0} ({1:dddd d MMMM yyyy})' -f $_.Title, $_.Date)
          }
