name: gummbah

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "5 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on:  self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Volkskrant, UncommonSense.Rss -Scope CurrentUser -Force

      - name: Update feed
        shell: pwsh
        run: |
          Get-Gummbah
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description "<img src='$($_.Body)'/>" `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Gummbah' `
            -Link 'https://www.volkskrant.nl/cultuur-media/gummbah~b3681e20/' `
            -Description 'Gummbah'
          | Set-Content -Path ./data/gummbah.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
