name: heindekort

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "45 4 * * 1-6"
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Parool, UncommonSense.Rss -Scope CurrentUser

      - name: Update feed
        shell: pwsh
        run: |
          Get-HeinDeKort
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description "<img src='$($_.Body)'/>" `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Hein de Kort' `
            -Link 'https://www.parool.nl/gs-b738ae8f' `
            -Description 'Hein de Kort'
          | Set-Content -Path ./data/heindekort.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
