name: heindekort2

on:
    schedule:
        - cron: "45 6 * * 1-6"
    workflow_dispatch:

jobs:
    run:
        runs-on: self-hosted

        steps:
            - name: Install required PowerShell modules
              shell: pwsh
              run: |
                  Set-PSRepository PSGallery -InstallationPolicy Trusted
                  Install-Module UncommonSense.Parool, UncommonSense.Pushover -Scope CurrentUser -Force

            - name: Send notification
              shell: pwsh
              env:
                  PUSHOVER_APP_HEINDEKORT: ${{secrets.PUSHOVER_APP_HEINDEKORT}}
                  PUSHOVER_USER_HEINDEKORT: ${{secrets.PUSHOVER_USER_HEINDEKORT}}
              run: |
                  Get-HeinDeKort
                  | Select-Object -First 1
                  | ForEach-Object {
                    Send-PushoverNotification `
                      -ApplicationToken $env:PUSHOVER_APP_HEINDEKORT `
                      -Recipient $env:PUSHOVER_USER_HEINDEKORT `
                      -Attachment $_.Body `
                      -Message ($_.Date).ToString('dddd d MMM yyyy') `
                      -Title 'Hein de Kort'
                    }
