name: ikjes

on:
  schedule:
    - cron: "40 6 * * 1-6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: UncommonSense.Hap, UncommonSense.Nrc, UncommonSense.Rss -Force

      - name: Update feed
        shell: pwsh
        run: |
          Get-Ikje
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description $_.Body `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Ikje' `
            -Link 'https://nrc.nl/rubriek/ikje' `
            -Description 'Lezers zijn de auteur van deze rubriek. Een Ikje is een persoonlijke ervaring of anekdote in maximaal 120 woorden. Insturen via ik@nrc.nl.'
          | Set-Content -Path ./data/ikje.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
