name: meewind

on:
  # schedule:
  #   - cron: "0 9 * * *"
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  retrievedata:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Meewind -Scope CurrentUser

      - name: Update fund data
        env:
          DataFileName: ./data/meewind.xml
        shell: pwsh
        run: |
          Write-Host "$($env:DataFileName)"
          $Data = if (Test-Path -Path "$env:DataFileName") { Import-CliXml -Path "$env:DataFileName" -ErrorAction SilentlyContinue } else { @{} }
          Get-MeewindFundPrice | ForEach-Object {
            if (-not $Data[$_.Fund]) { $Data[$_.Fund] = @{}}
            $Data[$_.Fund][$_.Date] = $_.Price
          }
          $Data | Export-CliXml -Path "$env:DataFileName"

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git add .
          git commit -am 'Updated data file'
          git push

  sendnotification:
    needs: retrievedata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Pushover -Scope CurrentUser
