name: meewind

on:
  # schedule:
  #   - cron: "0 9 * * *"
  # push:
  #   branches:
  #     - "master"
  workflow_dispatch:

jobs:
  retrievedata:
    runs-on: ubuntu-latest
    env:
      DataFolderName: ./data/meewind

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Meewind -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update fund data
        shell: pwsh
        run: |
          $DataFileName = "$(Get-Date -Format FileDate).xml"
          $DataFilePath = Join-Path -Path $env:DataFolderName -ChildPath $DataFileName
          Get-MeewindFundPrice | Export-CliXml -Path $DataFilePath

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git add ./data/meewind/*
          git commit -am 'Updated data files'
          git push

  sendnotification:
    needs: retrievedata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Pushover -Scope CurrentUser

      - name: Clean-up data folder
        shell: pwsh
        run: |
          Get-ChildItem -Path $env:DataFolderName
          | Sort-Object Name -Descending
          | Select-Object -Skip 3
          | Remove-Item -Force

      - name: Send notification
        shell: pwsh
        run: |
          $Data = Get-ChildItem -Path $env:DataFolderName | Import-CliXml
          Write-Host $Data
