name: meewind

on:
  # schedule:
  #   - cron: "0 9 * * *"
  # push:
  #   branches:
  #     - "master"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DataFolderName: ./data/meewind

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Meewind, UncommonSense.Pushover -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update fund data
        shell: pwsh
        run: |
          $DataFileName = "$(Get-Date -Format FileDate).xml"
          $DataFilePath = Join-Path -Path $env:DataFolderName -ChildPath $DataFileName
          Get-MeewindFundPrice | Export-CliXml -Path $DataFilePath

      - name: Clean-up data folder
        shell: pwsh
        run: |
          Get-ChildItem -Path $env:DataFolderName
          | Sort-Object Name -Descending
          | Select-Object -Skip 3
          | Remove-Item -Force

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git add ./data/meewind/*
          git commit -am 'Updated data files'
          git push

      - name: Send notification
        shell: pwsh
        env:
          PUSHOVER_APP: ${{ secrets.PUSHOVER_APP_MEEWIND}}
          PUSHOVER_RECIPIENT: ${{secrets.PUSHOVER_RECIP_JUSTME}}
        run: |
          Get-ChildItem -Path $env:DataFolderName
          | Import-CliXml
          | Sort-Object -Property Fund, Date
          | Group-Object -Property Fund
          | ForEach-Object {
            Send-PushoverNotification `
                -ApplicationToken "$env:PUSHOVER_APP" `
                -Recipient "$env:PUSHOVER_RECIPIENT" `
                -Title "Meewind $($_.Name)" `
                -Html `
                -Message ($_.Group | ForEach-Object { '{0}: &eur;{1}' -f $_.Date.ToString('yyyy-MM-dd'), $_.Price})
          }
