name: meewind

on:
  # schedule:
  #   - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.PowerShell.Documentation -Scope CurrentUser

      - name: Update fund data
        shell: pwsh
        env:
        run: |
          GITHUB_WORKSPACE: ${{$GITHUB_WORKSPACE}}
          $Data = Import-CliXml -Path "$(env:GITHUB_WORKSPACE)/data/meewind.xml" -ErrorAction SilentlyContinue

  #       - name: Update readme
  #         run: |
  #           pwsh -Command "./Update-README.ps1"
  #       - name: Push changes to git repo
  #         run: |
  #           git config --global user.name 'Jan Hoek'
  #           git config --global user.email 'github@uncommonsense.nl'
  #           git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
  #           git add .
  #           git commit -am 'Updated readme'
  #           git push

  sendnotification:
    needs: update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
