name: npoluister

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Npo, UncommonSense.Hap, UncommonSense.Rss -Scope CurrentUser -Force

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-NpoLuister
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description "<img src='$($_.Image)'/><p>$($_.Synopsis)</p>" `
              -PubDate (Get-Date) }
          | New-RssFeed `
            -Title 'NPO Luister' `
            -Link 'https://npo.nl/aanbod/npo-luister' `
            -Description 'NPO Luister'
          | Set-Content -Path ./data/npoluister.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
