name: opml

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Opml -Scope CurrentUser

      - name: Generate OPML document
        shell: pwsh
        run: |
          Get-ChildItem -Path ./data/*.xml
          | ForEach-Object {
            $CurrentFile = $_
            $Channel = ([xml](Get-Content -Path $CurrentFile.FullName)).rss.channel
            New-OpmlOutline -Text $Channel.Title.InnerText -Type rss -Attribute @{ title = $Channel.Title.InnerText; version = 'rss'; htmlUrl = $Channel.Link.InnerText; xmlUrl = "https://raw.githubusercontent.com/jhoek/kibitzr/master/data/$($CurrentFile.Name)" }
          }
          | New-OpmlDocument -Title kibitzr
          | Set-Content ./data/kibitzr.opml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
