name: overseks

on:
  schedule:
    - cron: "40 4 * * 4"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Nrc, UncommonSense.Rss -Scope CurrentUser

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-OverSeks
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description (($_.Body | ForEach-Object { $_.Trim()} | Where-Object {$_} | ForEach-Object { "<p>$($_)</p>"}) -join "`n") `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Over seks' `
            -Link 'https://www.nrc.nl/rubriek/over-seks/' `
            -Description 'Over seks'
          | Set-Content -Path ./data/overseks.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
