name: quote

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install PowerShell module
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Pushover

      - name: Send Pushover notification
        shell: pwsh
        env:
          PUSHOVER_APP: ${{ secrets.PUSHOVER_APP_QUOTES}}
          PUSHOVER_RECIPIENT: ${{secrets.PUSHOVER_RECIP_JUSTME}}
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $Quote = (Invoke-RestMethod -Uri http://quotes.rest/qod.json?category=funny).contents.quotes.quote
          Send-PushoverNotification `
              -ApplicationToken "$env:PUSHOVER_APP" `
              -Recipient "$env:PUSHOVER_RECIPIENT" `
              -Title 'Quote of the Day' `
              -Message $Quote `
              -Priority Low
