name: sportserviceveenendaal

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.SportServiceVeenendaal, UncommonSense.iCalendar -Scope CurrentUser

      - name: Update calendar file
        shell: pwsh
        run: |
          Get-SportServiceVeenendaalOpeningHour -Verbose
          | Where-Object Activity -in 'Recreatief zwemmen', 'Banenzwemmen'
          | Where-Object Facitily -in 'Buitenbad'
          | ForEach-Object { New-CalendarEvent -Start ($_.From) -End ($_.To) -Summary "$($_.Activity) in het $($_.Facility)" }
          | Export-Calendar -Name 'Sportservice Veenendaal' -Path (Join-Path -Path data -ChildPath sportserviceveenendaal.ics)

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
