name: test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        shell: pwsh
        run: |
            $DutchCulture = Get-Culture nl-NL
            $MyDateTime = Get-Date -Day 1 -Month 6
            $MyDateTimeAsText = $MyDateTime.ToString('d MMM', $DutchCulture)
            Write-Host $MyDateTimeAsText
            $Parsed = ([DateTime]::ParseExact($MyDateTimeAsText, 'd MMM', $DutchCulture))
            Write-Host $Parsed
