name: tomjanssen

on:
    schedule:
        - cron: "0 5 * * 3"
    workflow_dispatch:

jobs:
    run:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2

            - name: Install required PowerShell modules
              shell: pwsh
              run: |
                  Set-PSRepository PSGallery -InstallationPolicy Trusted
                  Install-Module UncommonSense.Hap, UncommonSense.Trouw, UncommonSense.Rss -Scope CurrentUser -Force

            - name: Update feed
              shell: pwsh
              run: |
                  Get-TomJanssen
                  | Select-Object -First 10
                  | ForEach-Object {
                    New-RssFeedItem `
                      -ID $_.Url `
                      -Title $_.Title `
                      -Description "<img src='$($_.Body)'/>" `
                      -PubDate $_.Date }
                  | New-RssFeed `
                    -Title 'Tom Janssen' `
                    -Link 'https://www.trouw.nl/cartoons/tom-janssen~b46c7f64/' `
                    -Description 'Tom Janssen'
                  | Set-Content -Path ./data/tomjanssen.xml

            - name: Commit and push feed
              shell: bash
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git pull
                  git add .
                  git commit -m "generated" || echo "No changes to commit"
                  git push
