name: tvguide

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DataFolderName: ./data/tvguide

    steps:
      - uses: actions/checkout@v2

      - name: Install html-xml-utils
        run: sudo apt-get install -y html-xml-utils

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.TvGuide, UncommonSense.iCalendar -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update tv guide data
        shell: pwsh
        run: |
          $Channels = @{
              'npo-1'    = 'NPO 1'
              'npo-2'    = 'NPO 2'
              'npo-3'    = 'NPO 3'
              'bbc-one'  = 'BBC One'
              'bbc-two'  = 'BBC Two'
              'bbc-four' = 'BBC Four'
          }

          $Channels.Keys.ForEach{
              $CurrentChannel = $_
              $CurrentFileName = Join-Path -Path Env:DataFolderName -ChildPath "$CurrentChannel.ics"
              $Entries = Get-TvGuide -Channel $CurrentChannel
              $IsFirst = $true

              $Entries.ForEach{
                  if (-not $IsFirst )
                  {
                      # Report previous entry
                      $End = $_.DateTime
                      New-CalendarEvent -Start $Start -End $End -Summary $Summary
                  }

                  # Prepare for reporting current entry
                  $IsFirst = $false
                  $Start = $_.DateTime
                  $Summary = $_.Title
              } | Export-Calendar -Name $Channels[$CurrentChannel] -Path $CurrentFileName
          }

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git add ./data/tvguide/*
          git commit -am 'Updated tvguide files'
          git push
