name: twitter

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install PowerShell module
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Pushover

      - name: Send Pushover notification
        shell: pwsh
        env:
          PUSHOVER_APP: ${{ secrets.PUSHOVER_APP_TWITTER}}
          PUSHOVER_RECIPIENT: ${{secrets.PUSHOVER_RECIP_JUSTME}}
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $Message = ''
          $Priority = 'Normal'
          $Title = ''

          try
          {
              $Response = Invoke-WebRequest -Uri 'https://mobile.twitter.com/jhoek'

              $Message = switch ($true)
              {
                  ($Response.StatusCode -ne 200)
                  {
                      "Oops. Status code $($Response.StatusCode)"
                      break
                  }

                  $true
                  {
                      $Title = $Response.Content | pup 'title text{}' --plain
                  }

                  ($Title -notin 'joel mori (@jhoek) | Twitter', 'joel mori (@jhoek) on Twitter')
                  {
                      "Page title is now '$Title'"
                      $Priority = 'High'
                      break
                  }

                  $true
                  {
                      $Priority = 'Lowest'
                      "Page title is still '$Title'"
                  }
              }
          }
          catch
          {
              $Message = $_.Message
          }

          if ($Message)
          {
              Send-PushoverNotification `
                  -ApplicationToken "$env:PUSHOVER_APP" `
                  -Recipient "$env:PUSHOVER_RECIPIENT" `
                  -Title 'twitter.com/jhoek' `
                  -Message $Message `
                  -Priority $Priority `
                  -SupplementaryUrl 'https://twitter.com/jhoek'
          }
