name: watchdog

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Find latest updates
        shell: pwsh
        run: |
          $Body =
          Get-ChildItem -Path ./data/*.xml
          | ForEach-Object {
            $CurrentFile = $_

            Select-Xml -Path $_.FullName -XPath '/rss/channel/item/pubDate/text()'
            | Select-Object -ExpandProperty Node
            | Select-Object -ExpandProperty Value
            | ForEach-Object { [DateTime]::ParseExact($_, 'ddd, d MMM yyyy HH:mm:ss zzz', [CultureInfo]::InvariantCulture) }
            | Sort-Object -Descending
            | Select-Object -First 1
            | ForEach-Object { "$($CurrentFile.Name): $_" }
          }

          New-RssFeedItem -Title "Watchdog $(Get-Date)" -Description $Body
          | New-RssFeed -Title Watchdog -Description Watchdog -Link 'http://github.com/jhoek/kibitzr'
          | Set-Content -Path ./data/watchdog.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
