name: woord

on:
  schedule:
    - cron: "0 13 * * 1-6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.Nrc, UncommonSense.Rss -Scope CurrentUser

      - name: Update feed
        shell: pwsh
        run: |
          Get-Woord
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description $_.Body `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Woord' `
            -Link 'https://nrc.nl/rubriek/woord' `
            -Description 'Woord'
          | Set-Content -Path ./data/woord.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
