name: zomeravondgesprek

on:
  schedule:
    - cron: "45 8 * * 5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Nrc, UncommonSense.Rss -Scope CurrentUser

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-Zomeravondgesprek
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description ($_.Body -join "`n") `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title Zomeravondgesprek `
            -Link 'https://www.nrc.nl/rubriek/zomeravondgesprek/' `
            -Description Zomeravondgesprek
          | Set-Content -Path ./data/zomeravondgesprek.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
